server:
  port: 8080

spring:
  application:
    name: CyberStrikeAI
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cbai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  ai:
    openai:
      api-key: ${}
      base-url: https://papi.zhile.in
      chat:
        options:
          model: qwen3-coder-plus

# Logging
logging:
  level:
    com.cyberstrike: DEBUG
    org.springframework: INFO

security:
  tools-dir: ../tools

